os: linux
language: ruby
branches:
  only:
  - source
before_install:
  - gem update --system
  - gem install bundler
  - nvm install lts/erbium
  - nvm use lts/erbium
cache:
  bundler: true
  npm: true
install:
  - bundle install --jobs=3 --retry=3
  - npm ci
script:
  - JEKYLL_ENV=production ./node_modules/webpack-cli/bin/cli.js && bundle exec jekyll build --destination site
deploy:
  edge: true
  provider: pages
  local_dir: ./site
  target_branch: master
  email: deploy@travis-ci.org
  name: Deployment Bot
  token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: source
