
# Build settings
markdown: kramdown
highlighter: rouge
exclude: ['Gemfile*', 'vendor', '.idea', '.vscode', 'node_modules', 'package*', 'libs', 'webpack.config.js', 'babel.config.json']
plugins:
  - jekyll-paginate-v2

webpack:
  entry:
    - "assets/_js/bundle.js"
    - "assets/_scss/main.scss"
  cache_directory: '.jekyll-webpack'
  output:
    path: "assets/"

permalink: pretty

pagination:
  enabled: true
  per_page: 5

defaults:
  -
    scope:
      path: "_post" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
