
# Build settings
markdown: kramdown
highlighter: rouge
exclude: ['vendor', '.idea', '.vscode','node_modules', 'libs']
plugins:
  - jekyll-paginate-v2

babel:
  entry: "assets/js/bundle.js"
  output:
    path: "assets/js/"
    filename: "bundle.js"

permalink: pretty

pagination:
  enabled: true
  per_page: 5

defaults:
  -
    scope:
      path: "_post" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
