
#site settings
port: 8208
url: "http://eokoneyo.github.io"
title: "Eyo O. Eyo"
tagline: "Frontend Engineer, with a passion for building performant web experiences that scales."
description: "Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur."

#blog settings
blogName: The Cactus blog
paginate: 5
paginate_path: "blog/page:num"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
exclude: ['vendor', '.idea', '.vscode','node_modules', 'libs']
plugins:
  - jekyll-paginate

defaults:
  -
    scope:
      path: "_post" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

socials:
  - title: LinkedIn
    url: "https://www.linkedin.com/in/eyo-eyo-9a027a96/"
  - title: GitHub
    url: "https://github.com/eokoneyo"

babel:
  entry: 'assets/js/bundle.js'
  output:
    path: 'assets/js/'
    filename: 'bundle.js'
