
# Build settings
markdown: kramdown
highlighter: rouge
exclude:
  - 'Gemfile*'
  - 'vendor'
  - '.idea'
  - '.vscode'
  - 'node_modules'
  - 'package*'
  - 'libs'
  - 'webpack.config.js'
  - 'babel.config.json'
  - 'README.md'
  - 'CNAME'

plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-cloudinary

webpack:
  entry:
    - "assets/_js/client/index.js"
    - "assets/_scss/styles.scss"
  cache_directory: '.jekyll-webpack'
  output:
    path: "assets/"
    service_worker: true

cloudinary:
  cloud_name: 'dzd5dpyjo'
  only_prod: true
  verbose: true
  presets:
    post_photo:
      attributes:
        class: 'post_photo'
    profile_photo:
      attributes:
        class: 'photo-block__image'

search_data:
  filename: "search-data.json"
  output_path: "assets/"

permalink: /:categories/:title

pagination:
  enabled: true
  per_page: 5

defaults:
  -
    scope:
      path: "_post" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
