# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter: shiki

exclude:
  - 'Gemfile*'
  - 'vendor'
  - '.idea'
  - '.vscode'
  - '.jekyll-cache'
  - 'node_modules'
  - 'package*'
  - 'libs'
  - 'webpack.config.js'
  - 'babel.config.json'
  - 'tsconfig.json'
  - 'README.md'
  - 'coverage'
  - 'jest.json'
  - '.yarn'
  - 'yarn.lock'

plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-cloudinary
  - octopress-minify-html

webpack:
  entry:
    - "assets/_scripts/client/index.ts"
    - "assets/_scss/styles.scss"
  cache_directory: '.jekyll-webpack'
  output:
    path: "assets/"
    service_worker: true

cloudinary:
  cloud_name: 'dzd5dpyjo'
  only_prod: true
  verbose: true
  presets:
    image_zoom:
      figure: never
      attributes:
        class: 'image-zoom__preview js-image-zoom__preview'
        loading: lazy
    profile_photo:
      attributes:
        class: 'photo-block__image'

# config for generated data used to run search client side
search_data:
  filename: "search-data.json"
  output_path: "assets/"

# config for jekyll-paginate-v2
pagination:
  enabled: true
  per_page: 5

# site-wide permalink configuration
permalink: /:categories/:title

defaults:
  -
    scope:
      path: "_posts" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
