
#site settings
port: 8208
url: "http://eokoneyo.github.io"
title: "Eyo O. Eyo"
brandname: The Cactus
aboutDescription: Akri di yum
contactInfoHeader: Contact Me
contactInfoDescription: 
twitterHandle: maziey93
github: eokoneyo
copyrightBrandname: The Cactus
copyrightYear: 2014
ownerImageLocation: img/black.jpg 

#blog settings
blogName: The Cactus blog
blogDescription: Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.
blogTagLine: Another Jekyll blog
paginate: 5
paginate_path: "blog/page:num"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
exclude: ['.idea', '.vscode','node_modules', 'libs']
plugins:
  - jekyll-paginate
  - jekyll-babel

defaults:
  -
    scope:
      path: "_post" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

babel:
  entry: 'assets/js/bundle.js'
  output:
    path: 'assets/es6/'
    filename: 'bundlerrrd.js'
