#site settings
title: "Eyo O. Eyo"
seo_description: "Eyo O. Eyo is a Frontend Engineer, currently based in Berlin."
tagline: "Faber est Suae Quisque Fortunae"
description: >
  Frontend Engineer, with a strong focus in building performant web experiences that scale.
  Originally from Nigeria, I currently live in Berlin and work at HelloFresh.

headerLinks:
  - title: Blog
    path: "/blog"

socials:
  - title: LinkedIn
    url: "https://www.linkedin.com/in/eyo-eyo-9a027a96/"
  - title: GitHub
    url: "https://github.com/eokoneyo"

google_analytics: "UA-103572320-2"

#blog settings
blogName: The Cactus blog
paginate: 5
paginate_path: "blog/page:num"

# Build settings
markdown: kramdown
permalink: /blog/:categories/:year/:month/:day/:title/
highlighter: rouge
exclude: ['vendor', '.idea', '.vscode','node_modules', 'libs']
plugins:
  - jekyll-paginate

babel:
  entry: 'assets/js/bundle.js'
  output:
    path: 'assets/js/'
    filename: 'bundle.js'

defaults:
  -
    scope:
      path: "_post" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
