name: Code Health Check

on: [push]

jobs:
  code-health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Install Dependencies
        run: npm ci
      - name: Lint
        run: npm lint
      - name: Test
        run: npm test
